import type { Product, ProductCategory } from "@/types/product";

export interface CategoryInfo {
  title: ProductCategory;
  description: string;
  image: string;
}

export const categories: CategoryInfo[] = [
  {
    title: "Bath Bars",
    description: "Luxurious handcrafted goat milk and botanical oil cleansing bars",
    image: "/api/images/goat_milk_lavender_bar",
  },
  {
    title: "Herbal Soaps",
    description: "Traditional Ayurvedic botanical formulations for glowing skin",
    image: "/api/images/manjishtha_bath_bar",
  },
  {
    title: "Premium Shampoos",
    description: "Nourishing natural hair cleansers for root strength, growth & shine",
    image: "/api/images/hibiscus_shampoo",
  },
  {
    title: "Organic Skincare",
    description: "Antioxidant mists, glow gels, and calming aloe face treatments",
    image: "/api/images/rose_aura_toner",
  },
  {
    title: "Lip Care",
    description: "Shea butter and natural berry elixirs for soft, tinted lips",
    image: "/api/images/raspberry_lip_balm",
  },
  {
    title: "Cookies",
    description: "Wholesome millet and traditional grain cookies crafted for everyday snacking",
    image: "/api/images/thinai_cookies",
  },
  {
    title: "Best Sellers",
    description: "Beloved customer favorites rated 5-stars for pure organic potency",
    image: "/api/images/red_wine_glow_gel",
  },
  {
    title: "New Arrivals",
    description: "Fresh artisanal small-batch botanical releases",
    image: "/api/images/aloe_neem_tulsi_bar",
  },
  {
    title: "Gift Collections",
    description: "Thoughtfully curated self-care ritual sets for pampering",
    image: "/api/images/nalugumavu_bath_bar",
  },
];

export const products: Product[] = [
  // 1. Premium Pure Goat Milk with Lavender Essential Oil Bath Bar
  {
    id: "yuva-001",
    slug: "premium-pure-goat-milk-lavender-bath-bar",
    name: "Premium Pure Goat Milk with Lavender Essential Oil Bath Bar",
    price: 180,
    originalPrice: 240,
    size: "125g / 4.4 oz",
    category: "Bath Bars",
    collections: ["Bath Bars", "Herbal Soaps", "Best Sellers", "Gift Collections"],
    shortDescription: "A luxurious handcrafted bath bar enriched with pure goat milk and calming lavender essential oil. Deeply moisturizes and gently cleanses.",
    description: "A luxurious handcrafted bath bar enriched with pure goat milk and calming lavender essential oil. Deeply moisturizes, gently cleanses, and leaves the skin soft, refreshed, and delicately scented. Cold-processed over six weeks to preserve natural lactic acid, vitamins A and E, and essential fats.",
    badge: "Best Seller",
    image: "/api/images/goat_milk_lavender_bar",
    gallery: [
      "/api/images/goat_milk_lavender_bar",
      "https://images.unsplash.com/photo-1607006482602-765180037159?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=1200&q=80",
    ],
    rating: 4.9,
    reviews: 156,
    ingredients: [
      "Pure Fresh Goat Milk",
      "French Lavender Essential Oil",
      "Extra Virgin Olive Oil",
      "Unrefined Raw Shea Butter",
      "Cold-Pressed Coconut Oil",
      "Golden Jojoba Oil",
    ],
    benefits: [
      "Deeply moisturizes without stripping natural skin moisture barrier",
      "Calms stress and skin irritation with aromatic Bulgarian lavender",
      "Ultra-creamy rich lather preserved through cold-process crafting",
      "Provides gentle pH-balanced cleansing suitable for sensitive skin",
    ],
    directions: [
      "Work bar into a dense, velvety lather between wet hands or a natural loofah",
      "Gently massage lather over face and body in soothing circular motions",
      "Rinse thoroughly with warm water and let bar air-dry on a draining soap dish",
    ],
    skinType: ["Sensitive", "Dry", "Normal", "Eczema-Prone", "All Skin Types"],
    relatedSlugs: ["manjishtha-licorice-goat-milk-bath-bar", "charcoal-goat-milk-tea-tree-bath-bar", "rose-aura-refreshing-toner"],
    frequentlyBoughtWith: ["rose-aura-refreshing-toner", "raspberry-red-tint-lip-balm"],
    customerReviews: [
      {
        id: "rev-101",
        author: "Aaradhya S.",
        rating: 5,
        date: "3 days ago",
        title: "Incredible moisture & heavenly scent!",
        comment: "This goat milk soap is unlike anything I've bought in store. My skin feels like velvet after every bath, and the lavender aroma fills the entire bathroom.",
        verified: true,
      },
      {
        id: "rev-102",
        author: "Priya Nair",
        rating: 5,
        date: "1 week ago",
        title: "Cured my dry winter skin patches",
        comment: "I have ultra-sensitive dry skin that usually flakes. After using this bar for a week, my skin is calm, smooth, and completely nourished.",
        verified: true,
      },
    ],
  },

  // 2. Manjishtha, Licorice & Goat Milk Bath Bar
  {
    id: "yuva-002",
    slug: "manjishtha-licorice-goat-milk-bath-bar",
    name: "Manjishtha, Licorice & Goat Milk Bath Bar",
    price: 190,
    originalPrice: 250,
    size: "125g / 4.4 oz",
    category: "Bath Bars",
    collections: ["Bath Bars", "Herbal Soaps", "Best Sellers", "Organic Skincare"],
    shortDescription: "Traditional herbal bath bar made with Manjishtha, Licorice & Goat Milk to brighten dull skin and improve complexion.",
    description: "A traditional herbal bath bar made with Manjishtha, Licorice, and Goat Milk to brighten dull skin, improve complexion, and provide deep nourishment while maintaining healthy skin. The botanical synergism of Ayurvedic roots works naturally to diminish uneven pigmentation.",
    badge: "Ayurvedic Heritage",
    image: "/api/images/manjishtha_bath_bar",
    gallery: [
      "/api/images/manjishtha_bath_bar",
      "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=1200&q=80",
    ],
    rating: 4.9,
    reviews: 138,
    ingredients: [
      "Pure Farm Goat Milk",
      "Manjishtha (Indian Madder) Extract",
      "Licorice Root Powder & Extract",
      "Organic Virgin Coconut Oil",
      "Raw Cocoa Butter",
      "Sweet Almond Oil",
    ],
    benefits: [
      "Brightens dull skin and promotes a radiant, even skin tone",
      "Fades hyperpigmentation and sun blemishes naturally",
      "Nourishes deep skin layers with milk lipids and antioxidants",
      "Maintains optimal elasticity and youthful softness",
    ],
    directions: [
      "Apply lather directly onto wet body and face",
      "Allow the herbal root extract to rest on skin for 1-2 minutes for absorption",
      "Rinse thoroughly with clean lukewarm water",
    ],
    skinType: ["Dull Skin", "Uneven Tone", "Pigmented", "Combination", "All Skin Types"],
    relatedSlugs: ["red-wine-mulberry-glow-gel", "nalugumavu-bath-bar", "premium-pure-goat-milk-lavender-bath-bar"],
    frequentlyBoughtWith: ["red-wine-mulberry-glow-gel", "rose-aura-refreshing-toner"],
    customerReviews: [
      {
        id: "rev-201",
        author: "Meera K.",
        rating: 5,
        date: "2 weeks ago",
        title: "Noticeable brightening effect!",
        comment: "Manjishtha and licorice really work! My facial tan faded within two weeks of using this bath bar daily.",
        verified: true,
      },
    ],
  },

  // 3. Aloe, Neem, Tulsi & Kuppaimeni Bath Bar
  {
    id: "yuva-003",
    slug: "aloe-neem-tulsi-kuppaimeni-bath-bar",
    name: "Aloe, Neem, Tulsi & Kuppaimeni Bath Bar",
    price: 170,
    size: "125g / 4.4 oz",
    category: "Bath Bars",
    collections: ["Bath Bars", "Herbal Soaps", "New Arrivals", "Organic Skincare"],
    shortDescription: "Refreshing herbal cleansing bar with Aloe Vera, Neem, Tulsi & Kuppaimeni to purify skin and reduce acne naturally.",
    description: "A refreshing herbal cleansing bar formulated with Aloe Vera, Neem, Tulsi, and Kuppaimeni to help purify the skin, reduce acne, soothe irritation, and maintain healthy skin naturally. Packed with antibacterial herbal extracts that clarify clogged pores without stripping moisture.",
    badge: "Acne Control",
    image: "/api/images/aloe_neem_tulsi_bar",
    gallery: [
      "/api/images/aloe_neem_tulsi_bar",
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=1200&q=80",
    ],
    rating: 4.8,
    reviews: 94,
    ingredients: [
      "Fresh Aloe Vera Leaf Gel",
      "Cold-Pressed Neem Leaf Extract",
      "Holy Basil (Tulsi) Oil",
      "Indian Nettle (Kuppaimeni) Extract",
      "Cold-Pressed Castor Oil",
      "Turmeric Extract",
    ],
    benefits: [
      "Purifies pores and reduces body and facial acne breakouts",
      "Soothes skin redness, rashes, and inflammatory irritation",
      "Natural herbal defense against bacteria and environmental dirt",
      "Leaves skin feeling deeply clean, cool, and refreshed",
    ],
    directions: [
      "Lather between wet palms and apply gently over acne-prone skin",
      "Rinse thoroughly with cool or lukewarm water",
      "Use twice daily for optimal clarifying results",
    ],
    skinType: ["Acne-Prone", "Oily", "Sensitive", "Reactive Skin"],
    relatedSlugs: ["aloe-boosted-acne-face-gel", "charcoal-goat-milk-tea-tree-bath-bar"],
    frequentlyBoughtWith: ["aloe-boosted-acne-face-gel", "flaxseed-shampoo"],
    customerReviews: [
      {
        id: "rev-301",
        author: "Kavya Menon",
        rating: 5,
        date: "5 days ago",
        title: "Cleared my back acne!",
        comment: "The combination of Kuppaimeni and Neem in this bar is magical. My back acne cleared up completely!",
        verified: true,
      },
    ],
  },

  // 4. Charcoal & Goat Milk with Tea Tree Essential Oil Bath Bar
  {
    id: "yuva-004",
    slug: "charcoal-goat-milk-tea-tree-bath-bar",
    name: "Charcoal & Goat Milk with Tea Tree Essential Oil Bath Bar",
    price: 180,
    size: "125g / 4.4 oz",
    category: "Bath Bars",
    collections: ["Bath Bars", "Herbal Soaps", "Best Sellers"],
    shortDescription: "Activated charcoal combined with goat milk and tea tree essential oil to draw out impurities and control excess oil.",
    description: "Activated charcoal combined with nourishing goat milk and tea tree essential oil helps remove impurities, control excess oil, deeply cleanse pores, and leave skin feeling fresh. Charcoal draws out pollutants while goat milk prevents skin tightness.",
    badge: "Deep Detox",
    image: "/api/images/charcoal_tea_tree_bar",
    gallery: [
      "/api/images/charcoal_tea_tree_bar",
      "https://images.unsplash.com/photo-1607006482602-765180037159?auto=format&fit=crop&w=1200&q=80",
    ],
    rating: 4.8,
    reviews: 118,
    ingredients: [
      "Activated Bamboo Charcoal Powder",
      "Pure Goat Milk",
      "Tea Tree Essential Oil",
      "Virgin Coconut Oil",
      "Raw Shea Butter",
      "Eucalyptus Oil",
    ],
    benefits: [
      "Draws out micro-pollutants, dirt, and deep pore sebum",
      "Controls excess oiliness for a smooth matte finish",
      "Antimicrobial tea tree oil helps combat blemishes",
      "Goat milk cushions skin against dryness post-cleansing",
    ],
    directions: [
      "Massage creamy black lather over damp face and body",
      "Concentrate on oily T-zone, chest, or back areas",
      "Rinse clean with water and follow with moisturizer",
    ],
    skinType: ["Oily", "Congested", "Combination", "Acne-Prone"],
    relatedSlugs: ["aloe-neem-tulsi-kuppaimeni-bath-bar", "aloe-boosted-acne-face-gel"],
    frequentlyBoughtWith: ["aloe-boosted-acne-face-gel", "rose-aura-refreshing-toner"],
    customerReviews: [
      {
        id: "rev-401",
        author: "Rohan V.",
        rating: 5,
        date: "3 weeks ago",
        title: "Best detox soap ever",
        comment: "Great for post-workout showers. It cleanses deeply without leaving my face feeling dry or stretched.",
        verified: true,
      },
    ],
  },

  // 5. Nalugumavu Bath Bar
  {
    id: "yuva-005",
    slug: "nalugumavu-bath-bar",
    name: "Nalugumavu Bath Bar",
    price: 180,
    originalPrice: 220,
    size: "125g / 4.4 oz",
    category: "Bath Bars",
    collections: ["Bath Bars", "Herbal Soaps", "Gift Collections", "New Arrivals"],
    shortDescription: "Ayurvedic herbal bath bar that gently exfoliates, brightens skin texture, and provides a naturally healthy glow.",
    description: "Inspired by traditional Ayurvedic herbal care, this bath bar gently exfoliates, brightens the skin, improves texture, and provides a naturally healthy glow suitable for everyday use. Formulated with authentic Nalugumavu botanical scrub blend.",
    badge: "Royal Ayurvedic",
    image: "/api/images/nalugumavu_bath_bar",
    gallery: [
      "/api/images/nalugumavu_bath_bar",
      "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=1200&q=80",
    ],
    rating: 4.9,
    reviews: 86,
    ingredients: [
      "Nalugumavu Herbal Compound (Turmeric, Vetiver, Green Gram, Rose)",
      "Pure Coconut Oil",
      "Mahua Seed Oil",
      "Castor Oil",
      "Sandalwood Aroma",
    ],
    benefits: [
      "Gently buffs away dead skin cells for silky smoothness",
      "Brightens complexion and enhances natural golden glow",
      "Neutralizes body odor naturally with aromatic herbs",
      "Suitable for everyday natural gentle body exfoliation",
    ],
    directions: [
      "Rub bath bar over wet skin to release gentle botanical micro-granules",
      "Gently massage in circular motions to exfoliate skin surface",
      "Rinse with warm water for instant silky smoothness",
    ],
    skinType: ["All Skin Types", "Rough Skin", "Dull Skin"],
    relatedSlugs: ["manjishtha-licorice-goat-milk-bath-bar", "red-wine-bath-bar"],
    frequentlyBoughtWith: ["raspberry-red-tint-lip-balm", "hibiscus-shampoo"],
    customerReviews: [
      {
        id: "rev-501",
        author: "Divya R.",
        rating: 5,
        date: "1 month ago",
        title: "Smells like authentic South Indian spa!",
        comment: "This Nalugumavu bar is pure nostalgia. Soft exfoliation and leaves skin radiant and pleasantly fragrant.",
        verified: true,
      },
    ],
  },

  // 6. Red Wine Bath Bar
  {
    id: "yuva-006",
    slug: "red-wine-bath-bar",
    name: "Red Wine Bath Bar",
    price: 200,
    originalPrice: 260,
    size: "125g / 4.4 oz",
    category: "Bath Bars",
    collections: ["Bath Bars", "Herbal Soaps", "New Arrivals", "Gift Collections"],
    shortDescription: "Infused with antioxidant-rich red wine extracts to rejuvenate tired skin, improve elasticity, and promote radiance.",
    description: "Infused with antioxidant-rich red wine extracts to help rejuvenate tired skin, improve elasticity, reduce dullness, and promote naturally radiant skin. Formulated with high-potency grape resveratrol to defend skin against premature aging.",
    badge: "Antioxidant Rich",
    image: "/api/images/red_wine_bath_bar",
    gallery: [
      "/api/images/red_wine_bath_bar",
      "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=1200&q=80",
    ],
    rating: 4.9,
    reviews: 112,
    ingredients: [
      "Organic Red Wine Polyphenol Concentrate",
      "Grape Seed Oil & Extract",
      "Sweet Almond Oil",
      "Raw Shea Butter",
      "French Red Clay",
      "Vitamin E",
    ],
    benefits: [
      "Rejuvenates tired, stressed skin with resveratrol antioxidants",
      "Improves skin elasticity and firmness over time",
      "Reduces dullness for a glowing, youthfully flushed complexion",
      "Luxurious antioxidant lather that pampers the senses",
    ],
    directions: [
      "Lather bar in hands under warm shower stream",
      "Smooth rich pinkish lather over body and rinse thoroughly",
    ],
    skinType: ["Mature", "Dull", "Dry", "All Skin Types"],
    relatedSlugs: ["red-wine-mulberry-glow-gel", "nalugumavu-bath-bar"],
    frequentlyBoughtWith: ["red-wine-mulberry-glow-gel", "rose-aura-refreshing-toner"],
    customerReviews: [
      {
        id: "rev-601",
        author: "Shweta G.",
        rating: 5,
        date: "2 weeks ago",
        title: "Pure luxury in a bath bar",
        comment: "Super rich and leaves my skin glowing. Paired it with the Red Wine Glow Gel for maximum effect!",
        verified: true,
      },
    ],
  },

  // 7. Flaxseed Shampoo
  {
    id: "yuva-007",
    slug: "flaxseed-shampoo",
    name: "Flaxseed Shampoo",
    price: 220,
    originalPrice: 280,
    size: "250ml / 8.5 fl. oz.",
    category: "Premium Shampoos",
    collections: ["Premium Shampoos", "Best Sellers"],
    shortDescription: "A nourishing shampoo enriched with flaxseed extracts to strengthen hair roots, reduce hair fall, and provide natural shine.",
    description: "A nourishing shampoo enriched with flaxseed extracts to strengthen hair roots, reduce hair fall, improve hair texture, and provide natural shine. Loaded with plant-based Omega-3 fatty acids and lignans that fortify brittle strands from root to end.",
    badge: "Root Fortifying",
    image: "/api/images/flaxseed_shampoo",
    gallery: [
      "/api/images/flaxseed_shampoo",
      "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=1200&q=80",
    ],
    rating: 4.8,
    reviews: 140,
    ingredients: [
      "Cold-Pressed Flaxseed Mucilage Extract",
      "Hydrolyzed Keratin Protein",
      "Organic Aloe Vera Juice",
      "Moroccan Argan Oil",
      "Provitamin B5 (Panthenol)",
    ],
    benefits: [
      "Strengthens hair roots and minimizes hair fall during washes",
      "Improves strand thickness and natural hair elasticity",
      "Adds luminous natural gloss without silicone weight",
      "Gently cleanses scalp while maintaining moisture retention",
    ],
    directions: [
      "Massage generous amount onto wet scalp and work down hair strands",
      "Lather softly for 2 minutes to allow flaxseed nutrients to penetrate",
      "Rinse completely with water",
    ],
    skinType: ["Fine Hair", "Weak Hair Roots", "Thinning Hair", "All Hair Types"],
    relatedSlugs: ["hibiscus-shampoo", "coconut-milk-shampoo"],
    frequentlyBoughtWith: ["coconut-milk-shampoo", "rose-aura-refreshing-toner"],
    customerReviews: [
      {
        id: "rev-701",
        author: "Neha Sharma",
        rating: 5,
        date: "4 days ago",
        title: "Hair fall reduced by 70%",
        comment: "I noticed a significant drop in hair fall after just 3 washes with this flaxseed shampoo. My hair feels much stronger!",
        verified: true,
      },
    ],
  },

  // 8. Hibiscus Shampoo
  {
    id: "yuva-008",
    slug: "hibiscus-shampoo",
    name: "Hibiscus Shampoo",
    price: 210,
    size: "250ml / 8.5 fl. oz.",
    category: "Premium Shampoos",
    collections: ["Premium Shampoos", "New Arrivals", "Best Sellers"],
    shortDescription: "A botanical shampoo formulated with hibiscus to promote healthy hair growth, reduce dandruff, and nourish scalp.",
    description: "A botanical shampoo formulated with hibiscus to promote healthy hair growth, reduce dandruff, nourish the scalp, and leave hair soft and silky. Fresh hibiscus mucilage acts as a natural conditioner while shikakai cleanses gently.",
    badge: "Hair Growth",
    image: "/api/images/hibiscus_shampoo",
    gallery: [
      "/api/images/hibiscus_shampoo",
      "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1200&q=80",
    ],
    rating: 4.9,
    reviews: 125,
    ingredients: [
      "Organic Hibiscus Petal Extract",
      "Soapnut (Reetha) Extract",
      "Shikakai Extract",
      "Rosemary Essential Oil",
      "Fenugreek Seed Oil",
    ],
    benefits: [
      "Promotes faster, thicker natural hair growth",
      "Reduces dandruff flakes and alleviates itchy scalp",
      "Deeply nourishes scalp follicles with amino acids",
      "Leaves hair silky, bouncy, and easy to detangle",
    ],
    directions: [
      "Apply to soaking wet hair and massage scalp gently with fingertips",
      "Build up rich botanical lather and rinse thoroughly",
    ],
    skinType: ["Dandruff-Prone", "Dry Scalp", "Frizzy Hair", "Normal Hair"],
    relatedSlugs: ["flaxseed-shampoo", "coconut-milk-shampoo"],
    frequentlyBoughtWith: ["flaxseed-shampoo", "nalugumavu-bath-bar"],
    customerReviews: [
      {
        id: "rev-801",
        author: "Anjali Rao",
        rating: 5,
        date: "2 weeks ago",
        title: "Leaves hair so soft and scalp flake-free",
        comment: "Smells divine and keeps my scalp dandruff-free all week. Love the natural shine it gives my waves.",
        verified: true,
      },
    ],
  },

  // 9. Coconut Milk Shampoo
  {
    id: "yuva-009",
    slug: "coconut-milk-shampoo",
    name: "Coconut Milk Shampoo",
    price: 230,
    originalPrice: 290,
    size: "250ml / 8.5 fl. oz.",
    category: "Premium Shampoos",
    collections: ["Premium Shampoos", "Best Sellers", "Gift Collections"],
    shortDescription: "Rich coconut milk shampoo that deeply hydrates dry hair, repairs damaged strands, controls frizz, and restores softness.",
    description: "Rich coconut milk shampoo that deeply hydrates dry hair, repairs damaged strands, controls frizz, and restores softness and smoothness. Lauric acid in fresh coconut milk penetrates deep into hair cortex for intensive strand repair.",
    badge: "Deep Moisture",
    image: "/api/images/coconut_milk_shampoo",
    gallery: [
      "/api/images/coconut_milk_shampoo",
      "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=1200&q=80",
    ],
    rating: 4.9,
    reviews: 148,
    ingredients: [
      "Fresh Organic Coconut Milk",
      "Cold-Pressed Macadamia Nut Oil",
      "Hydrolyzed Wheat Protein",
      "Aloe Vera Juice",
      "Sweet Almond Oil",
    ],
    benefits: [
      "Deeply hydrates dry, brittle, or heat-styled hair strands",
      "Repairs split ends and strengthens compromised hair shaft",
      "Eliminates stubborn frizz for silky smooth hair control",
      "Restores natural shine, softness, and touchable bounce",
    ],
    directions: [
      "Dispense onto wet hair and massage from roots down to ends",
      "Lather thoroughly and rinse clean with water",
    ],
    skinType: ["Dry", "Damaged", "Frizzy", "Color-Treated Hair"],
    relatedSlugs: ["flaxseed-shampoo", "hibiscus-shampoo"],
    frequentlyBoughtWith: ["hibiscus-shampoo", "raspberry-red-tint-lip-balm"],
    customerReviews: [
      {
        id: "rev-901",
        author: "Tanya M.",
        rating: 5,
        date: "1 week ago",
        title: "Ultimate cure for frizzy hair!",
        comment: "My hair used to puff up in humidity. This coconut milk shampoo keeps it smooth, shiny, and hydrated.",
        verified: true,
      },
    ],
  },

  // 10. Rose Aura Refreshing Toner
  {
    id: "yuva-010",
    slug: "rose-aura-refreshing-toner",
    name: "Rose Aura Refreshing Toner",
    price: 200,
    originalPrice: 250,
    size: "100ml / 3.4 fl. oz.",
    category: "Organic Skincare",
    collections: ["Organic Skincare", "Best Sellers", "New Arrivals"],
    shortDescription: "A gentle facial toner infused with rose extracts that refreshes the skin, tightens pores, and balances oil production.",
    description: "A gentle facial toner infused with rose extracts that refreshes the skin, tightens pores, balances oil production, and provides instant hydration. Distilled from pure Kannauj Damask rose petals for an instant dewy skin refresh.",
    badge: "Hydration Mist",
    image: "/api/images/rose_aura_toner",
    gallery: [
      "/api/images/rose_aura_toner",
      "https://images.unsplash.com/photo-1608248597263-00079e9603f7?auto=format&fit=crop&w=1200&q=80",
    ],
    rating: 4.9,
    reviews: 165,
    ingredients: [
      "Steam-Distilled Rose Petal Hydrosol",
      "Pure Hyaluronic Acid",
      "Witch Hazel Extract",
      "Niacinamide (Vitamin B3)",
      "Aloe Vera Juice",
    ],
    benefits: [
      "Refreshes skin with an instant burst of cooling hydration",
      "Tightens and minimizes enlarged pores post-cleansing",
      "Balances skin pH and regulates oil secretion",
      "Enhances skin radiance and prepares skin for serums",
    ],
    directions: [
      "Close eyes and mist 2-3 pumps across clean face and neck",
      "Gently press into skin with fingertips until absorbed",
      "Use morning, night, or midday over makeup for a dewy boost",
    ],
    skinType: ["All Skin Types", "Sensitive", "Dry", "Dehydrated"],
    relatedSlugs: ["red-wine-mulberry-glow-gel", "raspberry-red-tint-lip-balm", "premium-pure-goat-milk-lavender-bath-bar"],
    frequentlyBoughtWith: ["red-wine-mulberry-glow-gel", "raspberry-red-tint-lip-balm"],
    customerReviews: [
      {
        id: "rev-1001",
        author: "Ishita D.",
        rating: 5,
        date: "2 days ago",
        title: "Pure rose heaven!",
        comment: "This toner smells like fresh roses in the morning. So soothing and instantly plumps up my skin.",
        verified: true,
      },
    ],
  },

  // 11. Red Wine & Mulberry Glow Gel
  {
    id: "yuva-011",
    slug: "red-wine-mulberry-glow-gel",
    name: "Red Wine & Mulberry Glow Gel",
    price: 240,
    originalPrice: 300,
    size: "50ml / 1.7 fl. oz.",
    category: "Organic Skincare",
    collections: ["Organic Skincare", "Best Sellers", "New Arrivals"],
    shortDescription: "Lightweight antioxidant-rich gel with Red Wine & Mulberry extracts that brightens skin and delivers a healthy glow.",
    description: "A lightweight antioxidant-rich gel with Red Wine and Mulberry extracts that helps brighten skin, improve texture, reduce pigmentation, and deliver a healthy glow. Non-greasy gel locks in dewy moisture with resveratrol nutrients.",
    badge: "Radiance Boost",
    image: "/api/images/red_wine_glow_gel",
    gallery: [
      "/api/images/red_wine_glow_gel",
      "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=1200&q=80",
    ],
    rating: 4.9,
    reviews: 172,
    ingredients: [
      "Red Wine Resveratrol Extract",
      "White Mulberry Bark Extract",
      "Niacinamide (5%)",
      "Sodium Hyaluronate",
      "Organic Aloe Vera Gel",
    ],
    benefits: [
      "Brightens dull complexion and fades dark spots",
      "Improves skin texture for glass-skin clarity",
      "Fights environmental damage with concentrated antioxidants",
      "Absorbs rapidly without leave-on stickiness",
    ],
    directions: [
      "Gently smooth a small amount over clean face and neck",
      "Pat lightly until fully absorbed morning and night",
    ],
    skinType: ["All Skin Types", "Dull Skin", "Combination", "Pigmented"],
    relatedSlugs: ["rose-aura-refreshing-toner", "red-wine-bath-bar", "manjishtha-licorice-goat-milk-bath-bar"],
    frequentlyBoughtWith: ["rose-aura-refreshing-toner", "red-wine-bath-bar"],
    customerReviews: [
      {
        id: "rev-1101",
        author: "Sunita M.",
        rating: 5,
        date: "1 week ago",
        title: "Glass skin achieved!",
        comment: "I apply this glow gel after the Rose Aura toner. My face looks radiant, hydrated, and so healthy!",
        verified: true,
      },
    ],
  },

  // 12. Aloe Boosted Acne Face Gel
  {
    id: "yuva-012",
    slug: "aloe-boosted-acne-face-gel",
    name: "Aloe Boosted Acne Face Gel",
    price: 210,
    size: "60ml / 2.0 fl. oz.",
    category: "Organic Skincare",
    collections: ["Organic Skincare", "New Arrivals"],
    shortDescription: "Soothing aloe vera gel specially formulated for acne-prone skin to calm inflammation, reduce redness & clarify.",
    description: "A soothing aloe vera gel specially formulated for acne-prone skin. Helps calm inflammation, reduce redness, hydrate the skin, and support a clearer complexion. Formulated with cold-extracted aloe vera and botanical acne-clarifiers.",
    badge: "Acne Relief",
    image: "/api/images/aloe_acne_gel",
    gallery: [
      "/api/images/aloe_acne_gel",
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=1200&q=80",
    ],
    rating: 4.8,
    reviews: 106,
    ingredients: [
      "Cold-Pressed Aloe Vera Inner Gel",
      "Australian Tea Tree Oil",
      "Neem Leaf Extract",
      "Kuppaimeni Herb Extract",
      "Gotu Kola (Centella)",
    ],
    benefits: [
      "Rapidly cools active breakouts and calms facial redness",
      "Reduces acne inflammation without stripping skin moisture",
      "Supports clearer, balanced complexion with daily use",
      "Ultra-lightweight oil-free formula that won't clog pores",
    ],
    directions: [
      "Smooth a thin coat over clean face morning and evening",
      "Apply extra dab directly onto active pimples as spot treatment",
    ],
    skinType: ["Acne-Prone", "Oily", "Reactive", "Sensitive"],
    relatedSlugs: ["aloe-neem-tulsi-kuppaimeni-bath-bar", "charcoal-goat-milk-tea-tree-bath-bar"],
    frequentlyBoughtWith: ["aloe-neem-tulsi-kuppaimeni-bath-bar", "rose-aura-refreshing-toner"],
    customerReviews: [
      {
        id: "rev-1201",
        author: "Vikram S.",
        rating: 5,
        date: "3 weeks ago",
        title: "Cooled my angry breakouts instantly",
        comment: "Very cooling and non-greasy. Reduced redness on my cheeks overnight. Highly recommended!",
        verified: true,
      },
    ],
  },

  // 13. Raspberry Red Tint Lip Balm
  {
    id: "yuva-013",
    slug: "raspberry-red-tint-lip-balm",
    name: "Raspberry Red Tint Lip Balm",
    price: 140,
    originalPrice: 180,
    size: "15g / 0.5 oz",
    category: "Lip Care",
    collections: ["Lip Care", "Organic Skincare", "Best Sellers", "New Arrivals", "Gift Collections"],
    shortDescription: "A nourishing lip balm enriched with raspberry extracts that deeply moisturizes dry lips with a soft natural red tint.",
    description: "A nourishing lip balm enriched with raspberry extracts that deeply moisturizes dry lips while adding a soft natural red tint for a healthy look. Hand-blended with raw shea butter and plant waxes for lasting comfort.",
    badge: "Natural Tint",
    image: "/api/images/raspberry_lip_balm",
    gallery: [
      "/api/images/raspberry_lip_balm",
      "https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=1200&q=80",
    ],
    rating: 4.9,
    reviews: 184,
    ingredients: [
      "Organic Raspberry Fruit Extract",
      "Unrefined Raw Shea Butter",
      "Cold-Pressed Sweet Almond Oil",
      "Pure Beeswax",
      "Vitamin E Oil",
    ],
    benefits: [
      "Deeply moisturizes and repairs dry, cracked lips",
      "Adds a flattering, soft natural red tint for healthy glow",
      "Protects lip barrier against harsh wind and sun dryness",
      "Silky non-sticky luxury butter texture",
    ],
    directions: [
      "Smooth over lips generously with clean fingertip or brush",
      "Reapply as needed throughout the day for hydration & blush tint",
    ],
    skinType: ["Dry Lips", "Chapped Lips", "All Skin Types"],
    relatedSlugs: ["rose-aura-refreshing-toner", "premium-pure-goat-milk-lavender-bath-bar"],
    frequentlyBoughtWith: ["rose-aura-refreshing-toner", "premium-pure-goat-milk-lavender-bath-bar"],
    customerReviews: [
      {
        id: "rev-1301",
        author: "Nisha Patel",
        rating: 5,
        date: "5 days ago",
        title: "The perfect natural lip flush!",
        comment: "Not heavy, not sticky. Gives my lips the prettiest natural berry red glow while keeping them super soft.",
        verified: true,
      },
    ],
  },

  // 14. Solam Cookies
  {
    id: "yuva-014",
    slug: "solam-cookies",
    name: "Solam Cookies",
    price: 180,
    originalPrice: 220,
    size: "300g",
    category: "Cookies",
    collections: ["Cookies", "New Arrivals"],
    shortDescription: "Wholesome cookies made with solam (sorghum), naturally rich in fibre.",
    description: "Wholesome cookies made with solam (sorghum), a traditional grain naturally rich in fibre. A tasty and satisfying choice for everyday snacking.",
    badge: "Traditional Grain",
    image: "/api/images/solam_cookies",
    gallery: [
      "/api/images/solam_cookies",
    ],
    rating: 4.9,
    reviews: 86,
    ingredients: [
      "Solam (Sorghum) Flour",
      "Organic Jaggery",
      "Pure Cow Ghee",
      "Cardamom",
    ],
    benefits: [
      "Rich in fibre for healthy digestion",
      "Made with traditional sorghum grain",
      "Wholesome everyday snack",
      "No artificial preservatives or refined sugars",
    ],
    directions: [
      "Enjoy as an everyday wholesome snack with herbal tea or warm milk",
    ],
    skinType: ["All Snack Lovers", "Gluten-Friendly"],
    relatedSlugs: ["thinai-cookies", "ragi-cookies", "rambu-cookies"],
    frequentlyBoughtWith: ["thinai-cookies", "ragi-cookies"],
    customerReviews: [
      {
        id: "rev-1401",
        author: "Lakshmi R.",
        rating: 5,
        date: "3 days ago",
        title: "Delicious and healthy!",
        comment: "My children love these solam cookies. Authentic flavor and not too sweet.",
        verified: true,
      },
    ],
  },

  // 15. Thinai Cookies
  {
    id: "yuva-015",
    slug: "thinai-cookies",
    name: "Thinai Cookies",
    price: 180,
    originalPrice: 220,
    size: "300g",
    category: "Cookies",
    collections: ["Cookies", "Best Sellers"],
    shortDescription: "Delicious cookies made with thinai (foxtail millet), valued for its light texture.",
    description: "Delicious cookies made with thinai (foxtail millet), a traditional grain valued for its light texture and nutritional profile.",
    badge: "Best Seller",
    image: "/api/images/thinai_cookies",
    gallery: [
      "/api/images/thinai_cookies",
    ],
    rating: 4.9,
    reviews: 112,
    ingredients: [
      "Thinai (Foxtail Millet) Flour",
      "Natural Unrefined Jaggery",
      "Pure Ghee",
      "Cardamom Powder",
    ],
    benefits: [
      "Rich in dietary fibre",
      "Traditional foxtail millet nutritional goodness",
      "Light and crispy everyday snack",
      "No artificial preservatives",
    ],
    directions: [
      "Pair with morning tea or afternoon snacks",
    ],
    skinType: ["All Snack Lovers"],
    relatedSlugs: ["solam-cookies", "ragi-cookies", "kavuni-cookies"],
    frequentlyBoughtWith: ["ragi-cookies", "kavuni-cookies"],
    customerReviews: [
      {
        id: "rev-1501",
        author: "Siddharth K.",
        rating: 5,
        date: "1 week ago",
        title: "Perfect teatime cookie!",
        comment: "Great crunch and subtle sweetness from jaggery. Perfect guilt-free snack.",
        verified: true,
      },
    ],
  },

  // 16. Ragi Cookies
  {
    id: "yuva-016",
    slug: "ragi-cookies",
    name: "Ragi Cookies",
    price: 170,
    originalPrice: 210,
    size: "300g",
    category: "Cookies",
    collections: ["Cookies", "Best Sellers"],
    shortDescription: "Nourishing cookies made with ragi (finger millet) with a satisfying crunch.",
    description: "Nourishing cookies made with ragi (finger millet), offering a wholesome combination of traditional grain goodness and satisfying crunch.",
    badge: "Calcium Rich",
    image: "/api/images/ragi_cookies",
    gallery: [
      "/api/images/ragi_cookies",
    ],
    rating: 4.8,
    reviews: 94,
    ingredients: [
      "Ragi (Finger Millet) Flour",
      "Organic Jaggery",
      "Pure Cow Ghee",
      "Cardamom",
    ],
    benefits: [
      "Rich in fibre and natural calcium",
      "Contains authentic finger millet (ragi)",
      "Wholesome nutrient-dense snack",
      "No artificial preservatives",
    ],
    directions: [
      "Ready to eat right out of the box",
    ],
    skinType: ["All Snack Lovers"],
    relatedSlugs: ["thinai-cookies", "rambu-cookies"],
    frequentlyBoughtWith: ["thinai-cookies", "rambu-cookies"],
    customerReviews: [
      {
        id: "rev-1601",
        author: "Meenakshi S.",
        rating: 5,
        date: "4 days ago",
        title: "Super rich Ragi flavor!",
        comment: "Tastes like authentic home-baked cookies. Good for health and very filling.",
        verified: true,
      },
    ],
  },

  // 17. Rambu Cookies
  {
    id: "yuva-017",
    slug: "rambu-cookies",
    name: "Rambu Cookies",
    price: 180,
    originalPrice: 230,
    size: "300g",
    category: "Cookies",
    collections: ["Cookies", "New Arrivals"],
    shortDescription: "Healthy homemade-style cookies made with rambu (pearl millet) and jaggery.",
    description: "Healthy homemade-style cookies made with rambu (pearl millet) and natural ingredients, crafted for a satisfying everyday snack.",
    badge: "Homemade Style",
    image: "/api/images/rambu_cookies",
    gallery: [
      "/api/images/rambu_cookies",
    ],
    rating: 4.9,
    reviews: 78,
    ingredients: [
      "Rambu (Pearl Millet / Bajra) Flour",
      "Natural Jaggery",
      "Pure Ghee",
      "Cardamom",
    ],
    benefits: [
      "Rich in fibre and minerals",
      "Traditional pearl millet recipe",
      "Made with jaggery",
      "No artificial preservatives",
    ],
    directions: [
      "Store in a cool dry airtight container after opening",
    ],
    skinType: ["All Snack Lovers"],
    relatedSlugs: ["solam-cookies", "kavuni-cookies"],
    frequentlyBoughtWith: ["kavuni-cookies", "solam-cookies"],
    customerReviews: [
      {
        id: "rev-1701",
        author: "Venkatesh P.",
        rating: 5,
        date: "2 weeks ago",
        title: "Loved the pearl millet flavor!",
        comment: "Satisfying texture and wholesome ingredients. Will order again!",
        verified: true,
      },
    ],
  },

  // 18. Kavuni Cookies
  {
    id: "yuva-018",
    slug: "kavuni-cookies",
    name: "Kavuni Cookies",
    price: 210,
    originalPrice: 260,
    size: "300g",
    category: "Cookies",
    collections: ["Cookies", "Best Sellers", "New Arrivals"],
    shortDescription: "Delicious cookies made with traditional antioxidant-rich kavuni black rice.",
    description: "Delicious cookies made with kavuni rice, a traditional black rice variety known for its distinctive colour and naturally occurring antioxidants.",
    badge: "Black Rice Heritage",
    image: "/api/images/kavuni_cookies",
    gallery: [
      "/api/images/kavuni_cookies",
    ],
    rating: 4.9,
    reviews: 142,
    ingredients: [
      "Kavuni (Black Rice) Flour",
      "Organic Jaggery",
      "Pure Ghee",
      "Nuts & Cardamom",
    ],
    benefits: [
      "Made with traditional black rice",
      "Rich in fibre and antioxidants",
      "Wholesome artisanal ingredients",
      "No artificial preservatives",
    ],
    directions: [
      "Enjoy as an exquisite heritage snacking experience",
    ],
    skinType: ["All Snack Lovers"],
    relatedSlugs: ["thinai-cookies", "ragi-cookies", "rambu-cookies"],
    frequentlyBoughtWith: ["thinai-cookies", "ragi-cookies"],
    customerReviews: [
      {
        id: "rev-1801",
        author: "Kavitha M.",
        rating: 5,
        date: "1 week ago",
        title: "Unique black rice cookie!",
        comment: "Kavuni rice cookies are so unique and tasty. Very rich and satisfying.",
        verified: true,
      },
    ],
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: ProductCategory): Product[] {
  return products.filter((p) => p.category === category || p.collections.includes(category));
}

