import type { Product, ProductCategory } from "@/types/product";

export interface CategoryInfo {
  title: ProductCategory;
  description: string;
  image: string;
}

export const categories: CategoryInfo[] = [
  {
    title: "Bath Bars",
    description: "Goat milk, botanical oils, and rich natural lather",
    image: "https://images.unsplash.com/photo-1607006482602-765180037159?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Luxury Herbal Soaps",
    description: "Nourishing cleansers for glossy, healthy skin & hair",
    image: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Organic Skincare",
    description: "Gentle glow rituals and calming botanicals",
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Natural Serums",
    description: "Tinted balms and elixirs for glass skin radiance",
    image: "https://images.unsplash.com/photo-1608248597263-00079e9603f7?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Gift Collections",
    description: "Thoughtfully curated ritual sets for self-care",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Best Sellers",
    description: "Most beloved formulas rated 5-stars by skincare lovers",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "New Arrivals",
    description: "Fresh small-batched herbal releases",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80",
  },
];

export const products: Product[] = [
  {
    id: "yuva-001",
    slug: "manjishtha-licorice-goat-milk-bath-bar",
    name: "Manjishtha, Licorice & Goat Milk Bath Bar",
    price: 16,
    originalPrice: 22,
    size: "125g / 4.4 oz",
    category: "Bath Bars",
    collections: ["Bath Bars", "Luxury Herbal Soaps", "Best Sellers", "Gift Collections"],
    shortDescription: "A luminous goat milk bath bar enriched with Manjishtha & Licorice root for radiant, velvety skin.",
    description: "Indulge in a creamy, velvety cleanse with our signature Manjishtha, Licorice & Goat Milk Bath Bar. Formulated with fresh farm-reared goat milk, wild harvested Manjishtha root, and clarifying Licorice extract, this cold-process bar works in synergy to even out skin tone, soothe redness, and leave your skin feeling soft, cushioned, and deeply nourished.",
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1607006482602-765180037159?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1607006482602-765180037159?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=1200&q=80",
    ],
    rating: 4.9,
    reviews: 142,
    ingredients: [
      "Goat Milk",
      "Manjishtha Root Extract",
      "Licorice Root Extract",
      "Shea Butter",
      "Almond Oil",
      "Olive Oil",
      "Coconut Oil",
    ],
    benefits: [
      "Deeply brightens & evens skin tone naturally",
      "Ultra-creamy rich goat milk lather that preserves skin lipids",
      "Calms skin irritation, redness, and dry patches",
      "Cold-processed over 6 weeks to preserve botanical potency",
    ],
    directions: [
      "Work into a rich, creamy lather between hands or washcloth with warm water",
      "Massage gently across damp face and body in circular motions",
      "Rinse thoroughly and rest bar on a well-draining wooden soap tray",
    ],
    skinType: ["Sensitive", "Dry", "Uneven Tone", "All Skin Types"],
    relatedSlugs: ["red-wine-glow-gel", "red-wine-toner", "flora-lumin-elixir-serum"],
    frequentlyBoughtWith: ["flora-lumin-elixir-serum", "red-wine-toner"],
    customerReviews: [
      {
        id: "rev-1",
        author: "Ananya P.",
        rating: 5,
        date: "2 weeks ago",
        title: "The creamiest soap I have ever used!",
        comment: "My skin usually feels tight after bathing, but this goat milk bar leaves it completely soft and hydrated.",
        verified: true,
      },
    ],
  },
  {
    id: "yuva-002",
    slug: "red-wine-glow-gel",
    name: "Red Wine Glow Gel",
    price: 19,
    originalPrice: 25,
    size: "50ml / 1.7 fl. oz.",
    category: "Organic Skincare",
    collections: ["Organic Skincare", "Best Sellers", "Featured"],
    shortDescription: "Antioxidant-rich red wine polyphenols & mulberry extract for an instant radiant glow.",
    description: "A weightless, hydrating face gel packed with resveratrol polyphenols, red wine extract, and Niacinamide. Illuminates tired skin, improves barrier elasticity, and provides a fresh dewy finish.",
    badge: "Featured",
    image: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1200&q=80",
    ],
    rating: 4.8,
    reviews: 110,
    ingredients: ["Red Wine Polyphenols", "Mulberry Extract", "Niacinamide", "Aloe Vera", "Hyaluronic Acid"],
    benefits: ["Boosts complexion luminosity", "Smooths skin texture", "Plumps fine lines"],
    directions: ["Apply a nickel-sized amount onto clean skin morning and night."],
    skinType: ["All Skin Types", "Dull Skin", "Combination"],
    relatedSlugs: ["red-wine-toner", "manjishtha-licorice-goat-milk-bath-bar"],
    frequentlyBoughtWith: ["red-wine-toner", "manjishtha-licorice-goat-milk-bath-bar"],
  },
  {
    id: "yuva-003",
    slug: "red-wine-toner",
    name: "Red Wine Toner",
    price: 17,
    size: "100ml / 3.4 fl. oz.",
    category: "Organic Skincare",
    collections: ["Organic Skincare", "Best Sellers"],
    shortDescription: "A balancing botanical facial mist infused with red wine antioxidants and rose water.",
    description: "Refreshes skin post-cleansing, tightens pores, and preps the skin for serum absorption.",
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1608248597263-00079e9603f7?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1608248597263-00079e9603f7?auto=format&fit=crop&w=1200&q=80",
    ],
    rating: 4.7,
    reviews: 92,
    ingredients: ["Red Wine Extract", "Rose Water", "Witch Hazel", "Aloe Vera"],
    benefits: ["Refreshes tired skin", "Minimizes pore appearance", "Balances pH levels"],
    directions: ["Spritz generously over face after cleansing."],
    skinType: ["Oily", "Combination", "Normal"],
    relatedSlugs: ["red-wine-glow-gel", "manjishtha-licorice-goat-milk-bath-bar"],
  },
  {
    id: "yuva-004",
    slug: "raspberry-red-tint-lip-balm",
    name: "Raspberry Red Tint Lip Balm",
    price: 13,
    size: "15g / 0.5 oz",
    category: "Organic Skincare",
    collections: ["Organic Skincare", "Best Sellers", "New Arrivals"],
    shortDescription: "Nourishing shea butter balm with organic raspberry extract for soft, cushiony rosy lips.",
    description: "Provides long-lasting hydration with a natural flush of rosy color. Made with pure beeswax, sweet almond oil, and wild raspberry.",
    badge: "New",
    image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=1200&q=80",
    ],
    rating: 4.9,
    reviews: 104,
    ingredients: ["Raspberry Extract", "Shea Butter", "Almond Oil", "Beeswax"],
    benefits: ["Deeply hydrates chapped lips", "Imparts a subtle rose tint", "Non-sticky comfort"],
    directions: ["Glide over lips as needed throughout the day."],
    skinType: ["All Skin Types"],
    relatedSlugs: ["manjishtha-licorice-goat-milk-bath-bar"],
  },
  {
    id: "yuva-005",
    slug: "aloe-boosted-acne-face-gel",
    name: "Aloe Boosted Acne Face Gel",
    price: 15,
    size: "60ml / 2.0 fl. oz.",
    category: "Organic Skincare",
    collections: ["Organic Skincare", "Featured", "Best Sellers"],
    shortDescription: "A soothing clarification gel with organic Aloe Vera, Tea Tree, and Kuppaimeni for acne control.",
    description: "Formulated specifically for acne-prone skin, this cooling face gel rapidly calms breakouts, reduces redness, and balances sebum production without drying.",
    badge: "Acne Care",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=1200&q=80",
    ],
    rating: 5.0,
    reviews: 128,
    ingredients: ["Organic Aloe Vera Gel", "Tea Tree Essential Oil", "Neem Leaf Extract", "Kuppaimeni", "Cucumber Extract"],
    benefits: [
      "Rapidly calms active breakouts and inflammation",
      "Lightweight hydration that absorbs instantly",
      "Prevents future clogged pores and blemishes",
    ],
    directions: [
      "Apply a smooth layer over cleansed face, focusing on acne-prone areas.",
      "Use morning and evening.",
    ],
    skinType: ["Acne-Prone", "Oily", "Sensitive", "Combination"],
    relatedSlugs: ["charcoal-tulsi-soap", "neem-toner"],
    frequentlyBoughtWith: ["charcoal-tulsi-soap", "neem-toner"],
    customerReviews: [
      {
        id: "rev-2",
        author: "Golden Amanda",
        rating: 5,
        date: "1 week ago",
        title: "Cleared my breakouts in 5 days!",
        comment: "This Aloe gel is so soothing and light. My skin absorbs it completely and it reduced my acne redness almost overnight.",
        verified: true,
      },
    ],
  },
  {
    id: "yuva-006",
    slug: "neem-toner",
    name: "Neem Toner",
    price: 10,
    size: "100ml / 3.4 fl. oz.",
    category: "Organic Skincare",
    collections: ["Organic Skincare", "Featured"],
    shortDescription: "Antimicrobial neem leaf water to clarify pores and balance oily skin.",
    description: "An invigorating herbal toner distilled from fresh neem leaves and sacred basil.",
    badge: "Herbal Care",
    image: "https://images.unsplash.com/photo-1547793548-7a0e7dfdb24f?auto=format&fit=crop&w=1200&q=80",
    gallery: ["https://images.unsplash.com/photo-1547793548-7a0e7dfdb24f?auto=format&fit=crop&w=1200&q=80"],
    rating: 4.6,
    reviews: 82,
    ingredients: ["Neem Leaf Water", "Tulsi Extract", "Green Tea"],
    benefits: ["Clarifies impurities", "Protects against bacterial acne"],
    directions: ["Spritz onto face after cleansing."],
    skinType: ["Oily", "Problem Skin"],
    relatedSlugs: ["aloe-boosted-acne-face-gel"],
  },
  {
    id: "yuva-007",
    slug: "charcoal-tulsi-soap",
    name: "Charcoal, Tulsi Soap",
    price: 15,
    size: "125g / 4.4 oz",
    category: "Bath Bars",
    collections: ["Bath Bars", "Luxury Herbal Soaps", "Featured"],
    shortDescription: "Activated charcoal & sacred Holy Basil for deep pore detoxification.",
    description: "Draws out environmental impurities and excess oil while soothing skin with Holy Basil.",
    badge: "Detox Bar",
    image: "https://images.unsplash.com/photo-1608248597263-00079e9603f7?auto=format&fit=crop&w=1200&q=80",
    gallery: ["https://images.unsplash.com/photo-1608248597263-00079e9603f7?auto=format&fit=crop&w=1200&q=80"],
    rating: 4.8,
    reviews: 98,
    ingredients: ["Activated Bamboo Charcoal", "Tulsi Extract", "Tea Tree Oil", "Goat Milk"],
    benefits: ["Deep pore detox", "Clears body acne", "Smooths skin texture"],
    directions: ["Lather gently over body and face, then rinse."],
    skinType: ["Oily", "Combination"],
    relatedSlugs: ["aloe-boosted-acne-face-gel"],
  },
  {
    id: "yuva-008",
    slug: "charcoal-coconut",
    name: "Charcoal, Coconut",
    price: 18,
    size: "125g / 4.4 oz",
    category: "Bath Bars",
    collections: ["Bath Bars", "Luxury Herbal Soaps", "Featured"],
    shortDescription: "Purifying charcoal combined with moisturizing virgin coconut oil.",
    description: "A balanced cleansing bar that detoxifies with charcoal while keeping skin soft with coconut lipids.",
    badge: "Hydrating Detox",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1200&q=80",
    gallery: ["https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1200&q=80"],
    rating: 4.7,
    reviews: 75,
    ingredients: ["Activated Charcoal", "Virgin Coconut Oil", "Shea Butter"],
    benefits: ["Nourishing cleanse", "Detoxifies skin pores"],
    directions: ["Lather with warm water."],
    skinType: ["Normal", "Dry", "Combination"],
    relatedSlugs: ["charcoal-tulsi-soap"],
  },
  {
    id: "yuva-009",
    slug: "flora-lumin-elixir-serum",
    name: "Flora Lumin Elixir Serum",
    price: 34,
    originalPrice: 42,
    size: "30ml / 1.0 fl. oz.",
    category: "Natural Serums",
    collections: ["Natural Serums", "Organic Skincare", "Best Sellers"],
    shortDescription: "A concentrated botanical elixir with flora extracts and almond oil for glass-skin radiance.",
    description: "Elevate your skin ritual with our flagship Flora Lumin Elixir Serum. A silky, high-potency concentrate infused with cold-extracted flora petals, sweet almond oil, virgin olive oil, rosehip seed oil, and botanical vitamin E.",
    badge: "Flagship Serum",
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1608248597263-00079e9603f7?auto=format&fit=crop&w=1200&q=80",
    ],
    rating: 5.0,
    reviews: 210,
    ingredients: ["Flora Petal Extracts", "Sweet Almond Oil", "Rosehip Oil", "Vitamin E"],
    benefits: ["Locks in intense hydration", "Restores glass-skin luminescence"],
    directions: ["Warm 3 drops between fingertips and press into skin."],
    skinType: ["All Skin Types", "Dry", "Mature"],
    relatedSlugs: ["manjishtha-licorice-goat-milk-bath-bar"],
  },
  {
    id: "yuva-010",
    slug: "nalugumavu-bath-bar",
    name: "Nalugumavu Bath Bar",
    price: 14,
    size: "125g / 4.4 oz",
    category: "Bath Bars",
    collections: ["Bath Bars", "Luxury Herbal Soaps", "New Arrivals"],
    shortDescription: "Traditional South Indian Nalangu Maavu herbal bath bar infused with wild turmeric.",
    description: "Crafted with authentic Nalangu Maavu herbal powder—a blend of wild Kasturi turmeric, green gram, sandalwood, and vetiver.",
    badge: "Glow Ritual",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1200&q=80",
    gallery: ["https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1200&q=80"],
    rating: 4.8,
    reviews: 94,
    ingredients: ["Nalugumavu Herbs", "Wild Turmeric", "Green Gram", "Sandalwood"],
    benefits: ["Gentle micro-exfoliation", "Natural golden radiance"],
    directions: ["Glide bar directly over wet skin."],
    skinType: ["Dull Skin", "All Skin Types"],
    relatedSlugs: ["manjishtha-licorice-goat-milk-bath-bar"],
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((product) => product.slug === slug);
}

export function getProductsByCategory(category: ProductCategory): Product[] {
  return products.filter((product) => product.category === category);
}

export function getProductsByCollection(collection: ProductCategory): Product[] {
  if (collection === "Bath Bars") {
    return products.filter((p) => p.category === "Bath Bars");
  }
  return products.filter((product) => product.collections.includes(collection));
}
